### ISSUE TITLE
Remove eslint-disable when possible

### ISSUE THREAD

**Issue by abdonrd** [IBM/kui#1759]
### Rules disabled manually

You can find all of them by looking for `<rule name>` in the source code.

#### Basic rules

- [ ] `node/no-deprecated-api` (5 results)
- [ ] `eqeqeq` (3 results)
- [ ] `no-control-regex` (1 result)
- [ ] `no-eval` (1 result)
- [x] #1942 `no-cond-assign` (1 result)
- [x] #1941 `no-unreachable` (1 result)
- [x] #1928 `promise/param-names` (1 result)

#### TypeScript rules

- [ ] `@typescript-eslint/explicit-function-return-type` (5759 results)
- [ ] `@typescript-eslint/no-explicit-any` (132 results) https://github.com/IBM/kui/issues/1926
- [ ] `@typescript-eslint/no-unused-vars` (40 results)
- [ ] `@typescript-eslint/no-var-requires` (34 results)
- [ ] `@typescript-eslint/explicit-member-accessibility` (26 results)
- [ ] `@typescript-eslint/ban-types` (12 results)
- [ ] `@typescript-eslint/no-use-before-define` (6 results)
- [ ] `@typescript-eslint/no-empty-interface` (4 results)
- [ ] `@typescript-eslint/no-object-literal-type-assertion` (1 result)
- [x] #1927 `@typescript-eslint/interface-name-prefix` (1 result)

**Comment by abdonrd** [comment]
Some examples:

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-bash-like/src/pty/client.ts#L40-L45

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/packages/app/src/models/ReplResponse.ts#L17

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-bash-like/src/lib/util/markdown.ts#L48

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-bash-like/src/lib/util/markdown.ts#L97

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-openwhisk/src/test/openwhisk3/run.ts#L40

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-tekton/src/model/resource.ts#L28

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-wrk/src/lib/scriptgen.ts#L51

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/packages/app/src/util/mimic-dom.ts#L119

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-openwhisk/src/lib/models/auth.ts#L127

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/packages/app/src/main/headless.ts#L145

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-bash-like/src/pty/server.ts#L84

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-k8s/src/lib/controller/kubectl.ts#L51

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts#L243

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-openwhisk/src/lib/cmds/openwhisk-core.ts#L1032

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-tutorials/src/lib/cmds/play.ts#L668

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/packages/app/src/webapp/cli.ts#L717

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-apache-composer/src/test/composer3/docs-introductory-scenario.ts#L65

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-tutorials/samples/%40tutorials/translation-demo/lib/en2shakespeare.js#L5

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/tools/travis/done-web.js#L15

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-apache-composer/src/lib/utility/parse.ts#L19

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/tools/travis/cleanBucket.js#L8

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-bash-like/src/lib/util/ascii-key-value-to-table.ts#L47

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/tools/travis/swapIntoPlace.js#L27

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-openwhisk/tests/lib/openwhisk/openwhisk.js#L59

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/packages/app/src/core/plugin-assembler.ts#L137

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-apache-composer/src/test/composer3/docs-introductory-scenario.ts#L65

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts#L374

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts#L375

https://github.com/IBM/kui/blob/f5d87da4caa6395416ee794595ebfa54f83e15c7/plugins/plugin-openwhisk/src/lib/cmds/actions/let.ts#L378

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/packages/app/src/core/repl.ts#L451

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/packages/app/src/core/plugin-assembler.ts#L155

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/packages/app/src/core/plugin-assembler.ts#L162

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/packages/app/src/core/plugins.ts#L79

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/packages/app/src/webapp/views/sidecar.ts#L1011

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-bash-like/src/lib/util/json.ts#L20

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-grid/src/lib/cmds/grid.ts#L170

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-grid/src/lib/util.ts#L328

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk/src/lib/models/openwhisk-entity.ts#L36

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk/src/lib/views/cli/activations/entity.ts#L32

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk/src/lib/views/cli/activations/list.ts#L579

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk/src/views.ts#L25

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk/src/views.ts#L31

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk-debug/src/plugin.ts#L148

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk-debug/src/plugin.ts#L182

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk-debug/src/plugin.ts#L550

https://github.com/IBM/kui/blob/83cef530d679ce82a64900df198f032b0f0a844c/plugins/plugin-openwhisk-debug/src/plugin.ts#L767
