### ISSUE TITLE
README.md is out of date

### ISSUE THREAD

**Issue by starpit** [IBM/kui#4047]
- [ ] screenshots are old (covered b #4085)
- [x]  no mention of how to enable kubectl kui plugin (covered by #4073)
- [x] --ui is no longer needed (nor supported) (covered by https://github.com/IBM/kui/pull/4062)
- [x]  references to plugin-kubeui have to go (covered by #4073)
- [x] eliminate docs/installation.md (covered by #4073)
- [x] don't mention boilerplate repo (covered by #4064 )
- [x] get rid of "some older documentation", both the mention of it in README.md, and the file itself (covered by #4064 )
